on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: 🚚 Get latest code
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: git-test
          SLACK_COLOR: good
          SLACK_ICON: http://n336298b.beget.tech/.github/workflows/logo.png
          SLACK_MESSAGE: "Уважаемый ${{ $GITHUB_ACTOR }}  Ваши изменения уже на сайте можете проверять"
          SLACK_TITLE: "Доставка кода 🚚"
          SLACK_FOOTER: "Teachmeskills"
          SLACK_USERNAME: Github
          MSG_MINIMAL: true
